<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto

namespace Google\Events\Firebase\Database\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The data within all Firebase Real Time Database reference events.
 *
 * Generated from protobuf message <code>google.events.firebase.database.v1.ReferenceEventData</code>
 */
class ReferenceEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * The original data for the reference.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     */
    protected $data = null;
    /**
     * The change in the reference data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     */
    protected $delta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Value $data
     *           The original data for the reference.
     *     @type \Google\Protobuf\Value $delta
     *           The change in the reference data.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Database\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The original data for the reference.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     * @return \Google\Protobuf\Value
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The original data for the reference.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->data = $var;

        return $this;
    }

    /**
     * The change in the reference data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     * @return \Google\Protobuf\Value
     */
    public function getDelta()
    {
        return $this->delta;
    }

    /**
     * The change in the reference data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setDelta($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->delta = $var;

        return $this;
    }

}

