<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1\BuildOptions;

use UnexpectedValueException;

/**
 * Supported VM sizes.
 *
 * Protobuf type <code>google.events.cloud.cloudbuild.v1.BuildOptions.MachineType</code>
 */
class MachineType
{
    /**
     * Standard machine type.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Highcpu machine with 8 CPUs.
     *
     * Generated from protobuf enum <code>N1_HIGHCPU_8 = 1;</code>
     */
    const N1_HIGHCPU_8 = 1;
    /**
     * Highcpu machine with 32 CPUs.
     *
     * Generated from protobuf enum <code>N1_HIGHCPU_32 = 2;</code>
     */
    const N1_HIGHCPU_32 = 2;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::N1_HIGHCPU_8 => 'N1_HIGHCPU_8',
        self::N1_HIGHCPU_32 => 'N1_HIGHCPU_32',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MachineType::class, \Google\Events\Cloud\Cloudbuild\V1\BuildOptions_MachineType::class);

