<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/v1/data.proto

namespace Google\Events\Firebase\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The data within all Firebase Real Time Database document events.
 *
 * Generated from protobuf message <code>google.events.firebase.v1.DocumentEventData</code>
 */
class DocumentEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * The original data for the document.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     */
    protected $data = null;
    /**
     * The change in the document data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     */
    protected $delta = null;
    /**
     * The matches from wildcards specified in the event subscription, to the
     * values of those wildcards in the document name. For example,
     * a subscription to
     * `/projects/my_project/databases/(default)/documents/users/{username}`
     * matching a document with name
     * `/projects/my_project/databases/(default)/documents/users/marie`
     * would result in a mapping of `'username': 'marie'`.
     *
     * Generated from protobuf field <code>map<string, string> wildcards = 3;</code>
     */
    private $wildcards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Value $data
     *           The original data for the document.
     *     @type \Google\Protobuf\Value $delta
     *           The change in the document data.
     *     @type array|\Google\Protobuf\Internal\MapField $wildcards
     *           The matches from wildcards specified in the event subscription, to the
     *           values of those wildcards in the document name. For example,
     *           a subscription to
     *           `/projects/my_project/databases/(default)/documents/users/{username}`
     *           matching a document with name
     *           `/projects/my_project/databases/(default)/documents/users/marie`
     *           would result in a mapping of `'username': 'marie'`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The original data for the document.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     * @return \Google\Protobuf\Value
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The original data for the document.
     *
     * Generated from protobuf field <code>.google.protobuf.Value data = 1;</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->data = $var;

        return $this;
    }

    /**
     * The change in the document data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     * @return \Google\Protobuf\Value
     */
    public function getDelta()
    {
        return $this->delta;
    }

    /**
     * The change in the document data.
     *
     * Generated from protobuf field <code>.google.protobuf.Value delta = 2;</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setDelta($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->delta = $var;

        return $this;
    }

    /**
     * The matches from wildcards specified in the event subscription, to the
     * values of those wildcards in the document name. For example,
     * a subscription to
     * `/projects/my_project/databases/(default)/documents/users/{username}`
     * matching a document with name
     * `/projects/my_project/databases/(default)/documents/users/marie`
     * would result in a mapping of `'username': 'marie'`.
     *
     * Generated from protobuf field <code>map<string, string> wildcards = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getWildcards()
    {
        return $this->wildcards;
    }

    /**
     * The matches from wildcards specified in the event subscription, to the
     * values of those wildcards in the document name. For example,
     * a subscription to
     * `/projects/my_project/databases/(default)/documents/users/{username}`
     * matching a document with name
     * `/projects/my_project/databases/(default)/documents/users/marie`
     * would result in a mapping of `'username': 'marie'`.
     *
     * Generated from protobuf field <code>map<string, string> wildcards = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setWildcards($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->wildcards = $arr;

        return $this;
    }

}

