<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/data.proto

namespace Google\Events\Cloud\Audit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Additional information about a potentially long-running operation with which
 * a log entry is associated.
 *
 * Generated from protobuf message <code>google.events.cloud.audit.v1.LogEntryOperation</code>
 */
class LogEntryOperation extends \Google\Protobuf\Internal\Message
{
    /**
     * An arbitrary operation identifier. Log entries with the same
     * identifier are assumed to be part of the same operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * An arbitrary producer identifier. The combination of `id` and
     * `producer` must be globally unique. Examples for `producer`:
     * `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
     *
     * Generated from protobuf field <code>string producer = 2;</code>
     */
    protected $producer = '';
    /**
     * True if this is the first log entry in the operation.
     *
     * Generated from protobuf field <code>bool first = 3;</code>
     */
    protected $first = false;
    /**
     * True if this is the last log entry in the operation.
     *
     * Generated from protobuf field <code>bool last = 4;</code>
     */
    protected $last = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           An arbitrary operation identifier. Log entries with the same
     *           identifier are assumed to be part of the same operation.
     *     @type string $producer
     *           An arbitrary producer identifier. The combination of `id` and
     *           `producer` must be globally unique. Examples for `producer`:
     *           `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
     *     @type bool $first
     *           True if this is the first log entry in the operation.
     *     @type bool $last
     *           True if this is the last log entry in the operation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Cloud\Audit\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * An arbitrary operation identifier. Log entries with the same
     * identifier are assumed to be part of the same operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * An arbitrary operation identifier. Log entries with the same
     * identifier are assumed to be part of the same operation.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * An arbitrary producer identifier. The combination of `id` and
     * `producer` must be globally unique. Examples for `producer`:
     * `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
     *
     * Generated from protobuf field <code>string producer = 2;</code>
     * @return string
     */
    public function getProducer()
    {
        return $this->producer;
    }

    /**
     * An arbitrary producer identifier. The combination of `id` and
     * `producer` must be globally unique. Examples for `producer`:
     * `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
     *
     * Generated from protobuf field <code>string producer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProducer($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer = $var;

        return $this;
    }

    /**
     * True if this is the first log entry in the operation.
     *
     * Generated from protobuf field <code>bool first = 3;</code>
     * @return bool
     */
    public function getFirst()
    {
        return $this->first;
    }

    /**
     * True if this is the first log entry in the operation.
     *
     * Generated from protobuf field <code>bool first = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFirst($var)
    {
        GPBUtil::checkBool($var);
        $this->first = $var;

        return $this;
    }

    /**
     * True if this is the last log entry in the operation.
     *
     * Generated from protobuf field <code>bool last = 4;</code>
     * @return bool
     */
    public function getLast()
    {
        return $this->last;
    }

    /**
     * True if this is the last log entry in the operation.
     *
     * Generated from protobuf field <code>bool last = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setLast($var)
    {
        GPBUtil::checkBool($var);
        $this->last = $var;

        return $this;
    }

}

