<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/data.proto

namespace Google\Events\Cloud\Audit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identity delegation history of an authenticated service account.
 *
 * Generated from protobuf message <code>google.events.cloud.audit.v1.ServiceAccountDelegationInfo</code>
 */
class ServiceAccountDelegationInfo extends \Google\Protobuf\Internal\Message
{
    protected $Authority;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\FirstPartyPrincipal $first_party_principal
     *           First party (Google) identity as the real authority.
     *     @type \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\ThirdPartyPrincipal $third_party_principal
     *           Third party identity as the real authority.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Cloud\Audit\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * First party (Google) identity as the real authority.
     *
     * Generated from protobuf field <code>.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipal first_party_principal = 1;</code>
     * @return \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\FirstPartyPrincipal
     */
    public function getFirstPartyPrincipal()
    {
        return $this->readOneof(1);
    }

    /**
     * First party (Google) identity as the real authority.
     *
     * Generated from protobuf field <code>.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipal first_party_principal = 1;</code>
     * @param \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\FirstPartyPrincipal $var
     * @return $this
     */
    public function setFirstPartyPrincipal($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo_FirstPartyPrincipal::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Third party identity as the real authority.
     *
     * Generated from protobuf field <code>.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipal third_party_principal = 2;</code>
     * @return \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\ThirdPartyPrincipal
     */
    public function getThirdPartyPrincipal()
    {
        return $this->readOneof(2);
    }

    /**
     * Third party identity as the real authority.
     *
     * Generated from protobuf field <code>.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipal third_party_principal = 2;</code>
     * @param \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\ThirdPartyPrincipal $var
     * @return $this
     */
    public function setThirdPartyPrincipal($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo_ThirdPartyPrincipal::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAuthority()
    {
        return $this->whichOneof("Authority");
    }

}

