<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/data.proto

namespace Google\Events\Cloud\Audit\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\ThirdPartyPrincipal instead.
     * @deprecated
     */
    class ServiceAccountDelegationInfo_ThirdPartyPrincipal {}
}
class_exists(ServiceAccountDelegationInfo\ThirdPartyPrincipal::class);
@trigger_error('Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo_ThirdPartyPrincipal is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Audit\V1\ServiceAccountDelegationInfo\ThirdPartyPrincipal instead', E_USER_DEPRECATED);

