<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/auth/v1/data.proto

namespace Google\Events\Firebase\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The data within all Firebase Auth events.
 *
 * Generated from protobuf message <code>google.events.firebase.auth.v1.AuthEventData</code>
 */
class AuthEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * The user identifier in the Firebase app.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     */
    protected $uid = '';
    /**
     * The user's primary email, if set.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * Whether or not the user's primary email is verified.
     *
     * Generated from protobuf field <code>bool email_verified = 3;</code>
     */
    protected $email_verified = false;
    /**
     * The user's display name.
     *
     * Generated from protobuf field <code>string display_name = 4;</code>
     */
    protected $display_name = '';
    /**
     * The user's photo URL.
     *
     * Generated from protobuf field <code>string photo_URL = 5;</code>
     */
    protected $photo_URL = '';
    /**
     * Whether the user is disabled.
     *
     * Generated from protobuf field <code>bool disabled = 6;</code>
     */
    protected $disabled = false;
    /**
     * Additional metadata about the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.auth.v1.UserMetadata metadata = 7;</code>
     */
    protected $metadata = null;
    /**
     * User's info at the providers
     *
     * Generated from protobuf field <code>repeated .google.events.firebase.auth.v1.UserInfo provider_data = 8;</code>
     */
    private $provider_data;
    /**
     * The user's phone number.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     */
    protected $phone_number = '';
    /**
     * User's custom claims, typically used to define user roles and propagated
     * to an authenticated user's ID token.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct custom_claims = 10;</code>
     */
    protected $custom_claims = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *           The user identifier in the Firebase app.
     *     @type string $email
     *           The user's primary email, if set.
     *     @type bool $email_verified
     *           Whether or not the user's primary email is verified.
     *     @type string $display_name
     *           The user's display name.
     *     @type string $photo_URL
     *           The user's photo URL.
     *     @type bool $disabled
     *           Whether the user is disabled.
     *     @type \Google\Events\Firebase\Auth\V1\UserMetadata $metadata
     *           Additional metadata about the user.
     *     @type \Google\Events\Firebase\Auth\V1\UserInfo[]|\Google\Protobuf\Internal\RepeatedField $provider_data
     *           User's info at the providers
     *     @type string $phone_number
     *           The user's phone number.
     *     @type \Google\Protobuf\Struct $custom_claims
     *           User's custom claims, typically used to define user roles and propagated
     *           to an authenticated user's ID token.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Auth\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The user identifier in the Firebase app.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * The user identifier in the Firebase app.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * The user's primary email, if set.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * The user's primary email, if set.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Whether or not the user's primary email is verified.
     *
     * Generated from protobuf field <code>bool email_verified = 3;</code>
     * @return bool
     */
    public function getEmailVerified()
    {
        return $this->email_verified;
    }

    /**
     * Whether or not the user's primary email is verified.
     *
     * Generated from protobuf field <code>bool email_verified = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setEmailVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->email_verified = $var;

        return $this;
    }

    /**
     * The user's display name.
     *
     * Generated from protobuf field <code>string display_name = 4;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * The user's display name.
     *
     * Generated from protobuf field <code>string display_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * The user's photo URL.
     *
     * Generated from protobuf field <code>string photo_URL = 5;</code>
     * @return string
     */
    public function getPhotoURL()
    {
        return $this->photo_URL;
    }

    /**
     * The user's photo URL.
     *
     * Generated from protobuf field <code>string photo_URL = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoURL($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_URL = $var;

        return $this;
    }

    /**
     * Whether the user is disabled.
     *
     * Generated from protobuf field <code>bool disabled = 6;</code>
     * @return bool
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * Whether the user is disabled.
     *
     * Generated from protobuf field <code>bool disabled = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Additional metadata about the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.auth.v1.UserMetadata metadata = 7;</code>
     * @return \Google\Events\Firebase\Auth\V1\UserMetadata
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Additional metadata about the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.auth.v1.UserMetadata metadata = 7;</code>
     * @param \Google\Events\Firebase\Auth\V1\UserMetadata $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Auth\V1\UserMetadata::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * User's info at the providers
     *
     * Generated from protobuf field <code>repeated .google.events.firebase.auth.v1.UserInfo provider_data = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProviderData()
    {
        return $this->provider_data;
    }

    /**
     * User's info at the providers
     *
     * Generated from protobuf field <code>repeated .google.events.firebase.auth.v1.UserInfo provider_data = 8;</code>
     * @param \Google\Events\Firebase\Auth\V1\UserInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProviderData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Events\Firebase\Auth\V1\UserInfo::class);
        $this->provider_data = $arr;

        return $this;
    }

    /**
     * The user's phone number.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * The user's phone number.
     *
     * Generated from protobuf field <code>string phone_number = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * User's custom claims, typically used to define user roles and propagated
     * to an authenticated user's ID token.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct custom_claims = 10;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getCustomClaims()
    {
        return $this->custom_claims;
    }

    /**
     * User's custom claims, typically used to define user roles and propagated
     * to an authenticated user's ID token.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct custom_claims = 10;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setCustomClaims($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->custom_claims = $var;

        return $this;
    }

}

