<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/auth/v1/data.proto

namespace Google\Events\Firebase\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * User's info at the identity provider
 *
 * Generated from protobuf message <code>google.events.firebase.auth.v1.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The user identifier for the linked provider.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     */
    protected $uid = '';
    /**
     * The email for the linked provider.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * The display name for the linked provider.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     */
    protected $display_name = '';
    /**
     * The photo URL for the linked provider.
     *
     * Generated from protobuf field <code>string photo_URL = 4;</code>
     */
    protected $photo_URL = '';
    /**
     * The linked provider ID (e.g. "google.com" for the Google provider).
     *
     * Generated from protobuf field <code>string provider_id = 5;</code>
     */
    protected $provider_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uid
     *           The user identifier for the linked provider.
     *     @type string $email
     *           The email for the linked provider.
     *     @type string $display_name
     *           The display name for the linked provider.
     *     @type string $photo_URL
     *           The photo URL for the linked provider.
     *     @type string $provider_id
     *           The linked provider ID (e.g. "google.com" for the Google provider).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Auth\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The user identifier for the linked provider.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * The user identifier for the linked provider.
     *
     * Generated from protobuf field <code>string uid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * The email for the linked provider.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * The email for the linked provider.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * The display name for the linked provider.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * The display name for the linked provider.
     *
     * Generated from protobuf field <code>string display_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * The photo URL for the linked provider.
     *
     * Generated from protobuf field <code>string photo_URL = 4;</code>
     * @return string
     */
    public function getPhotoURL()
    {
        return $this->photo_URL;
    }

    /**
     * The photo URL for the linked provider.
     *
     * Generated from protobuf field <code>string photo_URL = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoURL($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_URL = $var;

        return $this;
    }

    /**
     * The linked provider ID (e.g. "google.com" for the Google provider).
     *
     * Generated from protobuf field <code>string provider_id = 5;</code>
     * @return string
     */
    public function getProviderId()
    {
        return $this->provider_id;
    }

    /**
     * The linked provider ID (e.g. "google.com" for the Google provider).
     *
     * Generated from protobuf field <code>string provider_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_id = $var;

        return $this;
    }

}

