<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/auth/v1/data.proto

namespace Google\Events\Firebase\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Additional metadata about the user.
 *
 * Generated from protobuf message <code>google.events.firebase.auth.v1.UserMetadata</code>
 */
class UserMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * The date the user was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    protected $created_at = null;
    /**
     * The date the user last signed in.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_signed_in_at = 2;</code>
     */
    protected $last_signed_in_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $created_at
     *           The date the user was created.
     *     @type \Google\Protobuf\Timestamp $last_signed_in_at
     *           The date the user last signed in.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Auth\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The date the user was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The date the user was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The date the user last signed in.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_signed_in_at = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getLastSignedInAt()
    {
        return $this->last_signed_in_at;
    }

    /**
     * The date the user last signed in.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_signed_in_at = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastSignedInAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_signed_in_at = $var;

        return $this;
    }

}

