<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing device informations.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.DeviceInfo</code>
 */
class DeviceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Device category.
     * Eg. tablet or mobile.
     *
     * Generated from protobuf field <code>string device_category = 1;</code>
     */
    protected $device_category = '';
    /**
     * Device brand name.
     * Eg. Samsung, HTC, etc.
     *
     * Generated from protobuf field <code>string mobile_brand_name = 2;</code>
     */
    protected $mobile_brand_name = '';
    /**
     * Device model name.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string mobile_model_name = 3;</code>
     */
    protected $mobile_model_name = '';
    /**
     * Device marketing name.
     * Eg. Galaxy S4 Mini
     *
     * Generated from protobuf field <code>string mobile_marketing_name = 4;</code>
     */
    protected $mobile_marketing_name = '';
    /**
     * Device model.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string device_model = 12;</code>
     */
    protected $device_model = '';
    /**
     * Device OS version when data capture ended.
     * Eg. 4.4.2
     *
     * Generated from protobuf field <code>string platform_version = 6;</code>
     */
    protected $platform_version = '';
    /**
     * Vendor specific device identifier. This is IDFV on iOS. Not used for
     * Android.
     * Example: "599F9C00-92DC-4B5C-9464-7971F01F8370"
     *
     * Generated from protobuf field <code>string device_id = 7;</code>
     */
    protected $device_id = '';
    /**
     * The type of the resettable_device_id is always IDFA on iOS and AdId
     * on Android.
     * Example: "71683BF9-FA3B-4B0D-9535-A1F05188BAF3"
     *
     * Generated from protobuf field <code>string resettable_device_id = 8;</code>
     */
    protected $resettable_device_id = '';
    /**
     * The user language.
     * Eg. "en-us", "en-za", "zh-tw", "jp"
     *
     * Generated from protobuf field <code>string user_default_language = 9;</code>
     */
    protected $user_default_language = '';
    /**
     * The timezone of the device when data was uploaded as seconds skew from UTC.
     *
     * Generated from protobuf field <code>int32 device_time_zone_offset_seconds = 10;</code>
     */
    protected $device_time_zone_offset_seconds = 0;
    /**
     * The device's Limit Ad Tracking setting.
     * When true, we cannot use device_id for remarketing, demographics or
     * influencing ads serving behaviour. However, we can use device_id for
     * conversion tracking and campaign attribution.
     *
     * Generated from protobuf field <code>bool limited_ad_tracking = 11;</code>
     */
    protected $limited_ad_tracking = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $device_category
     *           Device category.
     *           Eg. tablet or mobile.
     *     @type string $mobile_brand_name
     *           Device brand name.
     *           Eg. Samsung, HTC, etc.
     *     @type string $mobile_model_name
     *           Device model name.
     *           Eg. GT-I9192
     *     @type string $mobile_marketing_name
     *           Device marketing name.
     *           Eg. Galaxy S4 Mini
     *     @type string $device_model
     *           Device model.
     *           Eg. GT-I9192
     *     @type string $platform_version
     *           Device OS version when data capture ended.
     *           Eg. 4.4.2
     *     @type string $device_id
     *           Vendor specific device identifier. This is IDFV on iOS. Not used for
     *           Android.
     *           Example: "599F9C00-92DC-4B5C-9464-7971F01F8370"
     *     @type string $resettable_device_id
     *           The type of the resettable_device_id is always IDFA on iOS and AdId
     *           on Android.
     *           Example: "71683BF9-FA3B-4B0D-9535-A1F05188BAF3"
     *     @type string $user_default_language
     *           The user language.
     *           Eg. "en-us", "en-za", "zh-tw", "jp"
     *     @type int $device_time_zone_offset_seconds
     *           The timezone of the device when data was uploaded as seconds skew from UTC.
     *     @type bool $limited_ad_tracking
     *           The device's Limit Ad Tracking setting.
     *           When true, we cannot use device_id for remarketing, demographics or
     *           influencing ads serving behaviour. However, we can use device_id for
     *           conversion tracking and campaign attribution.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * Device category.
     * Eg. tablet or mobile.
     *
     * Generated from protobuf field <code>string device_category = 1;</code>
     * @return string
     */
    public function getDeviceCategory()
    {
        return $this->device_category;
    }

    /**
     * Device category.
     * Eg. tablet or mobile.
     *
     * Generated from protobuf field <code>string device_category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_category = $var;

        return $this;
    }

    /**
     * Device brand name.
     * Eg. Samsung, HTC, etc.
     *
     * Generated from protobuf field <code>string mobile_brand_name = 2;</code>
     * @return string
     */
    public function getMobileBrandName()
    {
        return $this->mobile_brand_name;
    }

    /**
     * Device brand name.
     * Eg. Samsung, HTC, etc.
     *
     * Generated from protobuf field <code>string mobile_brand_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMobileBrandName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile_brand_name = $var;

        return $this;
    }

    /**
     * Device model name.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string mobile_model_name = 3;</code>
     * @return string
     */
    public function getMobileModelName()
    {
        return $this->mobile_model_name;
    }

    /**
     * Device model name.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string mobile_model_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMobileModelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile_model_name = $var;

        return $this;
    }

    /**
     * Device marketing name.
     * Eg. Galaxy S4 Mini
     *
     * Generated from protobuf field <code>string mobile_marketing_name = 4;</code>
     * @return string
     */
    public function getMobileMarketingName()
    {
        return $this->mobile_marketing_name;
    }

    /**
     * Device marketing name.
     * Eg. Galaxy S4 Mini
     *
     * Generated from protobuf field <code>string mobile_marketing_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMobileMarketingName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile_marketing_name = $var;

        return $this;
    }

    /**
     * Device model.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string device_model = 12;</code>
     * @return string
     */
    public function getDeviceModel()
    {
        return $this->device_model;
    }

    /**
     * Device model.
     * Eg. GT-I9192
     *
     * Generated from protobuf field <code>string device_model = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_model = $var;

        return $this;
    }

    /**
     * Device OS version when data capture ended.
     * Eg. 4.4.2
     *
     * Generated from protobuf field <code>string platform_version = 6;</code>
     * @return string
     */
    public function getPlatformVersion()
    {
        return $this->platform_version;
    }

    /**
     * Device OS version when data capture ended.
     * Eg. 4.4.2
     *
     * Generated from protobuf field <code>string platform_version = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_version = $var;

        return $this;
    }

    /**
     * Vendor specific device identifier. This is IDFV on iOS. Not used for
     * Android.
     * Example: "599F9C00-92DC-4B5C-9464-7971F01F8370"
     *
     * Generated from protobuf field <code>string device_id = 7;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Vendor specific device identifier. This is IDFV on iOS. Not used for
     * Android.
     * Example: "599F9C00-92DC-4B5C-9464-7971F01F8370"
     *
     * Generated from protobuf field <code>string device_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

    /**
     * The type of the resettable_device_id is always IDFA on iOS and AdId
     * on Android.
     * Example: "71683BF9-FA3B-4B0D-9535-A1F05188BAF3"
     *
     * Generated from protobuf field <code>string resettable_device_id = 8;</code>
     * @return string
     */
    public function getResettableDeviceId()
    {
        return $this->resettable_device_id;
    }

    /**
     * The type of the resettable_device_id is always IDFA on iOS and AdId
     * on Android.
     * Example: "71683BF9-FA3B-4B0D-9535-A1F05188BAF3"
     *
     * Generated from protobuf field <code>string resettable_device_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setResettableDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->resettable_device_id = $var;

        return $this;
    }

    /**
     * The user language.
     * Eg. "en-us", "en-za", "zh-tw", "jp"
     *
     * Generated from protobuf field <code>string user_default_language = 9;</code>
     * @return string
     */
    public function getUserDefaultLanguage()
    {
        return $this->user_default_language;
    }

    /**
     * The user language.
     * Eg. "en-us", "en-za", "zh-tw", "jp"
     *
     * Generated from protobuf field <code>string user_default_language = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDefaultLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_default_language = $var;

        return $this;
    }

    /**
     * The timezone of the device when data was uploaded as seconds skew from UTC.
     *
     * Generated from protobuf field <code>int32 device_time_zone_offset_seconds = 10;</code>
     * @return int
     */
    public function getDeviceTimeZoneOffsetSeconds()
    {
        return $this->device_time_zone_offset_seconds;
    }

    /**
     * The timezone of the device when data was uploaded as seconds skew from UTC.
     *
     * Generated from protobuf field <code>int32 device_time_zone_offset_seconds = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setDeviceTimeZoneOffsetSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->device_time_zone_offset_seconds = $var;

        return $this;
    }

    /**
     * The device's Limit Ad Tracking setting.
     * When true, we cannot use device_id for remarketing, demographics or
     * influencing ads serving behaviour. However, we can use device_id for
     * conversion tracking and campaign attribution.
     *
     * Generated from protobuf field <code>bool limited_ad_tracking = 11;</code>
     * @return bool
     */
    public function getLimitedAdTracking()
    {
        return $this->limited_ad_tracking;
    }

    /**
     * The device's Limit Ad Tracking setting.
     * When true, we cannot use device_id for remarketing, demographics or
     * influencing ads serving behaviour. However, we can use device_id for
     * conversion tracking and campaign attribution.
     *
     * Generated from protobuf field <code>bool limited_ad_tracking = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setLimitedAdTracking($var)
    {
        GPBUtil::checkBool($var);
        $this->limited_ad_tracking = $var;

        return $this;
    }

}

