<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing information pertaining to the event.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.EventDimensions</code>
 */
class EventDimensions extends \Google\Protobuf\Internal\Message
{
    /**
     * The date on which this event was logged.
     * (YYYYMMDD format in the registered timezone of your app.)
     *
     * Generated from protobuf field <code>string date = 6;</code>
     */
    protected $date = '';
    /**
     * The name of this event.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * A repeated record of the parameters associated with this event.
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.AnalyticsValue> params = 2;</code>
     */
    private $params;
    /**
     * UTC client time when the event happened.
     *
     * Generated from protobuf field <code>int64 timestamp_micros = 4;</code>
     */
    protected $timestamp_micros = 0;
    /**
     * UTC client time when the previous event happened.
     *
     * Generated from protobuf field <code>int64 previous_timestamp_micros = 5;</code>
     */
    protected $previous_timestamp_micros = 0;
    /**
     * Value param in USD.
     *
     * Generated from protobuf field <code>double value_in_usd = 7;</code>
     */
    protected $value_in_usd = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $date
     *           The date on which this event was logged.
     *           (YYYYMMDD format in the registered timezone of your app.)
     *     @type string $name
     *           The name of this event.
     *     @type array|\Google\Protobuf\Internal\MapField $params
     *           A repeated record of the parameters associated with this event.
     *     @type int|string $timestamp_micros
     *           UTC client time when the event happened.
     *     @type int|string $previous_timestamp_micros
     *           UTC client time when the previous event happened.
     *     @type float $value_in_usd
     *           Value param in USD.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The date on which this event was logged.
     * (YYYYMMDD format in the registered timezone of your app.)
     *
     * Generated from protobuf field <code>string date = 6;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * The date on which this event was logged.
     * (YYYYMMDD format in the registered timezone of your app.)
     *
     * Generated from protobuf field <code>string date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * The name of this event.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of this event.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * A repeated record of the parameters associated with this event.
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.AnalyticsValue> params = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * A repeated record of the parameters associated with this event.
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.AnalyticsValue> params = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Events\Firebase\Analytics\V1\AnalyticsValue::class);
        $this->params = $arr;

        return $this;
    }

    /**
     * UTC client time when the event happened.
     *
     * Generated from protobuf field <code>int64 timestamp_micros = 4;</code>
     * @return int|string
     */
    public function getTimestampMicros()
    {
        return $this->timestamp_micros;
    }

    /**
     * UTC client time when the event happened.
     *
     * Generated from protobuf field <code>int64 timestamp_micros = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampMicros($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp_micros = $var;

        return $this;
    }

    /**
     * UTC client time when the previous event happened.
     *
     * Generated from protobuf field <code>int64 previous_timestamp_micros = 5;</code>
     * @return int|string
     */
    public function getPreviousTimestampMicros()
    {
        return $this->previous_timestamp_micros;
    }

    /**
     * UTC client time when the previous event happened.
     *
     * Generated from protobuf field <code>int64 previous_timestamp_micros = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreviousTimestampMicros($var)
    {
        GPBUtil::checkInt64($var);
        $this->previous_timestamp_micros = $var;

        return $this;
    }

    /**
     * Value param in USD.
     *
     * Generated from protobuf field <code>double value_in_usd = 7;</code>
     * @return float
     */
    public function getValueInUsd()
    {
        return $this->value_in_usd;
    }

    /**
     * Value param in USD.
     *
     * Generated from protobuf field <code>double value_in_usd = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setValueInUsd($var)
    {
        GPBUtil::checkDouble($var);
        $this->value_in_usd = $var;

        return $this;
    }

}

