<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Lifetime Value information about this user.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.LtvInfo</code>
 */
class LtvInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The Lifetime Value revenue of this user.
     *
     * Generated from protobuf field <code>double revenue = 1;</code>
     */
    protected $revenue = 0.0;
    /**
     * The currency corresponding to the revenue.
     *
     * Generated from protobuf field <code>string currency = 2;</code>
     */
    protected $currency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $revenue
     *           The Lifetime Value revenue of this user.
     *     @type string $currency
     *           The currency corresponding to the revenue.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The Lifetime Value revenue of this user.
     *
     * Generated from protobuf field <code>double revenue = 1;</code>
     * @return float
     */
    public function getRevenue()
    {
        return $this->revenue;
    }

    /**
     * The Lifetime Value revenue of this user.
     *
     * Generated from protobuf field <code>double revenue = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setRevenue($var)
    {
        GPBUtil::checkDouble($var);
        $this->revenue = $var;

        return $this;
    }

    /**
     * The currency corresponding to the revenue.
     *
     * Generated from protobuf field <code>string currency = 2;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * The currency corresponding to the revenue.
     *
     * Generated from protobuf field <code>string currency = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

}

