<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mesage containing marketing campaign information which acquired the user.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.TrafficSource</code>
 */
class TrafficSource extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the campaign which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_campaign = 2;</code>
     */
    protected $user_acquired_campaign = '';
    /**
     * The name of the network which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_source = 3;</code>
     */
    protected $user_acquired_source = '';
    /**
     * The name of the medium which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_medium = 4;</code>
     */
    protected $user_acquired_medium = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_acquired_campaign
     *           The name of the campaign which acquired the user.
     *     @type string $user_acquired_source
     *           The name of the network which acquired the user.
     *     @type string $user_acquired_medium
     *           The name of the medium which acquired the user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the campaign which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_campaign = 2;</code>
     * @return string
     */
    public function getUserAcquiredCampaign()
    {
        return $this->user_acquired_campaign;
    }

    /**
     * The name of the campaign which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_campaign = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAcquiredCampaign($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_acquired_campaign = $var;

        return $this;
    }

    /**
     * The name of the network which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_source = 3;</code>
     * @return string
     */
    public function getUserAcquiredSource()
    {
        return $this->user_acquired_source;
    }

    /**
     * The name of the network which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_source = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAcquiredSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_acquired_source = $var;

        return $this;
    }

    /**
     * The name of the medium which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_medium = 4;</code>
     * @return string
     */
    public function getUserAcquiredMedium()
    {
        return $this->user_acquired_medium;
    }

    /**
     * The name of the medium which acquired the user.
     *
     * Generated from protobuf field <code>string user_acquired_medium = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAcquiredMedium($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_acquired_medium = $var;

        return $this;
    }

}

