<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message containing information about the user associated with the event.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.UserDimensions</code>
 */
class UserDimensions extends \Google\Protobuf\Internal\Message
{
    /**
     * The user ID set via the setUserId API.
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * The time (in microseconds) at which the user first opened the app.
     *
     * Generated from protobuf field <code>int64 first_open_timestamp_micros = 2;</code>
     */
    protected $first_open_timestamp_micros = 0;
    /**
     * A repeated record of user properties set with the setUserProperty API.
     * https://firebase.google.com/docs/analytics/android/properties
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.UserPropertyValue> user_properties = 3;</code>
     */
    private $user_properties;
    /**
     * Device information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.DeviceInfo device_info = 4;</code>
     */
    protected $device_info = null;
    /**
     * User's geographic information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.GeoInfo geo_info = 5;</code>
     */
    protected $geo_info = null;
    /**
     * App information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AppInfo app_info = 6;</code>
     */
    protected $app_info = null;
    /**
     * Information about marketing campaign which acquired the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.TrafficSource traffic_source = 7;</code>
     */
    protected $traffic_source = null;
    /**
     * Information regarding the bundle in which these events were uploaded.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.ExportBundleInfo bundle_info = 8;</code>
     */
    protected $bundle_info = null;
    /**
     * Lifetime Value information about this user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.LtvInfo ltv_info = 9;</code>
     */
    protected $ltv_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *           The user ID set via the setUserId API.
     *     @type int|string $first_open_timestamp_micros
     *           The time (in microseconds) at which the user first opened the app.
     *     @type array|\Google\Protobuf\Internal\MapField $user_properties
     *           A repeated record of user properties set with the setUserProperty API.
     *           https://firebase.google.com/docs/analytics/android/properties
     *     @type \Google\Events\Firebase\Analytics\V1\DeviceInfo $device_info
     *           Device information.
     *     @type \Google\Events\Firebase\Analytics\V1\GeoInfo $geo_info
     *           User's geographic information.
     *     @type \Google\Events\Firebase\Analytics\V1\AppInfo $app_info
     *           App information.
     *     @type \Google\Events\Firebase\Analytics\V1\TrafficSource $traffic_source
     *           Information about marketing campaign which acquired the user.
     *     @type \Google\Events\Firebase\Analytics\V1\ExportBundleInfo $bundle_info
     *           Information regarding the bundle in which these events were uploaded.
     *     @type \Google\Events\Firebase\Analytics\V1\LtvInfo $ltv_info
     *           Lifetime Value information about this user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The user ID set via the setUserId API.
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * The user ID set via the setUserId API.
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * The time (in microseconds) at which the user first opened the app.
     *
     * Generated from protobuf field <code>int64 first_open_timestamp_micros = 2;</code>
     * @return int|string
     */
    public function getFirstOpenTimestampMicros()
    {
        return $this->first_open_timestamp_micros;
    }

    /**
     * The time (in microseconds) at which the user first opened the app.
     *
     * Generated from protobuf field <code>int64 first_open_timestamp_micros = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirstOpenTimestampMicros($var)
    {
        GPBUtil::checkInt64($var);
        $this->first_open_timestamp_micros = $var;

        return $this;
    }

    /**
     * A repeated record of user properties set with the setUserProperty API.
     * https://firebase.google.com/docs/analytics/android/properties
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.UserPropertyValue> user_properties = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getUserProperties()
    {
        return $this->user_properties;
    }

    /**
     * A repeated record of user properties set with the setUserProperty API.
     * https://firebase.google.com/docs/analytics/android/properties
     *
     * Generated from protobuf field <code>map<string, .google.events.firebase.analytics.v1.UserPropertyValue> user_properties = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setUserProperties($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Events\Firebase\Analytics\V1\UserPropertyValue::class);
        $this->user_properties = $arr;

        return $this;
    }

    /**
     * Device information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.DeviceInfo device_info = 4;</code>
     * @return \Google\Events\Firebase\Analytics\V1\DeviceInfo
     */
    public function getDeviceInfo()
    {
        return $this->device_info;
    }

    /**
     * Device information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.DeviceInfo device_info = 4;</code>
     * @param \Google\Events\Firebase\Analytics\V1\DeviceInfo $var
     * @return $this
     */
    public function setDeviceInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\DeviceInfo::class);
        $this->device_info = $var;

        return $this;
    }

    /**
     * User's geographic information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.GeoInfo geo_info = 5;</code>
     * @return \Google\Events\Firebase\Analytics\V1\GeoInfo
     */
    public function getGeoInfo()
    {
        return $this->geo_info;
    }

    /**
     * User's geographic information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.GeoInfo geo_info = 5;</code>
     * @param \Google\Events\Firebase\Analytics\V1\GeoInfo $var
     * @return $this
     */
    public function setGeoInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\GeoInfo::class);
        $this->geo_info = $var;

        return $this;
    }

    /**
     * App information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AppInfo app_info = 6;</code>
     * @return \Google\Events\Firebase\Analytics\V1\AppInfo
     */
    public function getAppInfo()
    {
        return $this->app_info;
    }

    /**
     * App information.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AppInfo app_info = 6;</code>
     * @param \Google\Events\Firebase\Analytics\V1\AppInfo $var
     * @return $this
     */
    public function setAppInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\AppInfo::class);
        $this->app_info = $var;

        return $this;
    }

    /**
     * Information about marketing campaign which acquired the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.TrafficSource traffic_source = 7;</code>
     * @return \Google\Events\Firebase\Analytics\V1\TrafficSource
     */
    public function getTrafficSource()
    {
        return $this->traffic_source;
    }

    /**
     * Information about marketing campaign which acquired the user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.TrafficSource traffic_source = 7;</code>
     * @param \Google\Events\Firebase\Analytics\V1\TrafficSource $var
     * @return $this
     */
    public function setTrafficSource($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\TrafficSource::class);
        $this->traffic_source = $var;

        return $this;
    }

    /**
     * Information regarding the bundle in which these events were uploaded.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.ExportBundleInfo bundle_info = 8;</code>
     * @return \Google\Events\Firebase\Analytics\V1\ExportBundleInfo
     */
    public function getBundleInfo()
    {
        return $this->bundle_info;
    }

    /**
     * Information regarding the bundle in which these events were uploaded.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.ExportBundleInfo bundle_info = 8;</code>
     * @param \Google\Events\Firebase\Analytics\V1\ExportBundleInfo $var
     * @return $this
     */
    public function setBundleInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\ExportBundleInfo::class);
        $this->bundle_info = $var;

        return $this;
    }

    /**
     * Lifetime Value information about this user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.LtvInfo ltv_info = 9;</code>
     * @return \Google\Events\Firebase\Analytics\V1\LtvInfo
     */
    public function getLtvInfo()
    {
        return $this->ltv_info;
    }

    /**
     * Lifetime Value information about this user.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.LtvInfo ltv_info = 9;</code>
     * @param \Google\Events\Firebase\Analytics\V1\LtvInfo $var
     * @return $this
     */
    public function setLtvInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\LtvInfo::class);
        $this->ltv_info = $var;

        return $this;
    }

}

