<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/data.proto

namespace Google\Events\Firebase\Analytics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Predefined (eg: LTV) or custom properties (eg: birthday) stored on client
 * side and associated with subsequent HitBundles.
 *
 * Generated from protobuf message <code>google.events.firebase.analytics.v1.UserPropertyValue</code>
 */
class UserPropertyValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Last set value of user property.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AnalyticsValue value = 1;</code>
     */
    protected $value = null;
    /**
     * UTC client time when user property was last set.
     *
     * Generated from protobuf field <code>int64 set_timestamp_usec = 2;</code>
     */
    protected $set_timestamp_usec = 0;
    /**
     * Index for user property (one-based).
     *
     * Generated from protobuf field <code>int32 index = 3;</code>
     */
    protected $index = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Events\Firebase\Analytics\V1\AnalyticsValue $value
     *           Last set value of user property.
     *     @type int|string $set_timestamp_usec
     *           UTC client time when user property was last set.
     *     @type int $index
     *           Index for user property (one-based).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Analytics\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * Last set value of user property.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AnalyticsValue value = 1;</code>
     * @return \Google\Events\Firebase\Analytics\V1\AnalyticsValue
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Last set value of user property.
     *
     * Generated from protobuf field <code>.google.events.firebase.analytics.v1.AnalyticsValue value = 1;</code>
     * @param \Google\Events\Firebase\Analytics\V1\AnalyticsValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Analytics\V1\AnalyticsValue::class);
        $this->value = $var;

        return $this;
    }

    /**
     * UTC client time when user property was last set.
     *
     * Generated from protobuf field <code>int64 set_timestamp_usec = 2;</code>
     * @return int|string
     */
    public function getSetTimestampUsec()
    {
        return $this->set_timestamp_usec;
    }

    /**
     * UTC client time when user property was last set.
     *
     * Generated from protobuf field <code>int64 set_timestamp_usec = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSetTimestampUsec($var)
    {
        GPBUtil::checkInt64($var);
        $this->set_timestamp_usec = $var;

        return $this;
    }

    /**
     * Index for user property (one-based).
     *
     * Generated from protobuf field <code>int32 index = 3;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Index for user property (one-based).
     *
     * Generated from protobuf field <code>int32 index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

}

