<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto

namespace GPBMetadata\Google\Events\Firebase\Database\V1;

class Data
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aee010a2d676f6f676c652f6576656e74732f66697265626173652f64617461626173652f76312f646174612e70726f746f1222676f6f676c652e6576656e74732e66697265626173652e64617461626173652e763122610a125265666572656e63654576656e744461746112240a046461746118012001280b32162e676f6f676c652e70726f746f6275662e56616c756512250a0564656c746118022001280b32162e676f6f676c652e70726f746f6275662e56616c7565422eaa022b476f6f676c652e4576656e74732e50726f746f6275662e46697265626173652e44617461626173652e5631620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

