<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/scheduler/v1/data.proto

namespace Google\Events\Cloud\Scheduler\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Scheduler job data.
 *
 * Generated from protobuf message <code>google.events.cloud.scheduler.v1.SchedulerJobData</code>
 */
class SchedulerJobData extends \Google\Protobuf\Internal\Message
{
    /**
     * The custom data the user specified when creating the scheduler source.
     *
     * Generated from protobuf field <code>bytes custom_data = 1;</code>
     */
    protected $custom_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $custom_data
     *           The custom data the user specified when creating the scheduler source.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Cloud\Scheduler\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The custom data the user specified when creating the scheduler source.
     *
     * Generated from protobuf field <code>bytes custom_data = 1;</code>
     * @return string
     */
    public function getCustomData()
    {
        return $this->custom_data;
    }

    /**
     * The custom data the user specified when creating the scheduler source.
     *
     * Generated from protobuf field <code>bytes custom_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomData($var)
    {
        GPBUtil::checkString($var, False);
        $this->custom_data = $var;

        return $this;
    }

}

