<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/data.proto

namespace Google\Events\Firebase\Remoteconfig\V1;

use UnexpectedValueException;

/**
 * What type of update was associated with the Remote Config template version.
 *
 * Protobuf type <code>google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin</code>
 */
class RemoteConfigUpdateOrigin
{
    /**
     * Catch-all for unrecognized values.
     *
     * Generated from protobuf enum <code>REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED = 0;</code>
     */
    const REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED = 0;
    /**
     * The update came from the Firebase UI.
     *
     * Generated from protobuf enum <code>CONSOLE = 1;</code>
     */
    const CONSOLE = 1;
    /**
     * The update came from the Remote Config REST API.
     *
     * Generated from protobuf enum <code>REST_API = 2;</code>
     */
    const REST_API = 2;
    /**
     * The update came from the Firebase Admin Node SDK.
     *
     * Generated from protobuf enum <code>ADMIN_SDK_NODE = 3;</code>
     */
    const ADMIN_SDK_NODE = 3;

    private static $valueToName = [
        self::REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED => 'REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED',
        self::CONSOLE => 'CONSOLE',
        self::REST_API => 'REST_API',
        self::ADMIN_SDK_NODE => 'ADMIN_SDK_NODE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

