<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/data.proto

namespace Google\Events\Firebase\Remoteconfig\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The data within all Firebase Remote Config events.
 *
 * Generated from protobuf message <code>google.events.firebase.remoteconfig.v1.RemoteConfigEventData</code>
 */
class RemoteConfigEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * The version number of the version's corresponding Remote Config template.
     *
     * Generated from protobuf field <code>int64 version_number = 1;</code>
     */
    protected $version_number = 0;
    /**
     * When the Remote Config template was written to the Remote Config server.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 2;</code>
     */
    protected $update_time = null;
    /**
     *  Aggregation of all metadata fields about the account that performed the update.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUser update_user = 3;</code>
     */
    protected $update_user = null;
    /**
     * The user-provided description of the corresponding Remote Config template.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Where the update action originated.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin update_origin = 5;</code>
     */
    protected $update_origin = 0;
    /**
     * What type of update was made.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType update_type = 6;</code>
     */
    protected $update_type = 0;
    /**
     * Only present if this version is the result of a rollback, and will be the
     * version number of the Remote Config template that was rolled-back to.
     *
     * Generated from protobuf field <code>int64 rollback_source = 7;</code>
     */
    protected $rollback_source = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version_number
     *           The version number of the version's corresponding Remote Config template.
     *     @type \Google\Protobuf\Timestamp $update_time
     *           When the Remote Config template was written to the Remote Config server.
     *     @type \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUser $update_user
     *            Aggregation of all metadata fields about the account that performed the update.
     *     @type string $description
     *           The user-provided description of the corresponding Remote Config template.
     *     @type int $update_origin
     *           Where the update action originated.
     *     @type int $update_type
     *           What type of update was made.
     *     @type int|string $rollback_source
     *           Only present if this version is the result of a rollback, and will be the
     *           version number of the Remote Config template that was rolled-back to.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Remoteconfig\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The version number of the version's corresponding Remote Config template.
     *
     * Generated from protobuf field <code>int64 version_number = 1;</code>
     * @return int|string
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * The version number of the version's corresponding Remote Config template.
     *
     * Generated from protobuf field <code>int64 version_number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * When the Remote Config template was written to the Remote Config server.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * When the Remote Config template was written to the Remote Config server.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->update_time = $var;

        return $this;
    }

    /**
     *  Aggregation of all metadata fields about the account that performed the update.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUser update_user = 3;</code>
     * @return \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUser
     */
    public function getUpdateUser()
    {
        return $this->update_user;
    }

    /**
     *  Aggregation of all metadata fields about the account that performed the update.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUser update_user = 3;</code>
     * @param \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUser $var
     * @return $this
     */
    public function setUpdateUser($var)
    {
        GPBUtil::checkMessage($var, \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUser::class);
        $this->update_user = $var;

        return $this;
    }

    /**
     * The user-provided description of the corresponding Remote Config template.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * The user-provided description of the corresponding Remote Config template.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Where the update action originated.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin update_origin = 5;</code>
     * @return int
     */
    public function getUpdateOrigin()
    {
        return $this->update_origin;
    }

    /**
     * Where the update action originated.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin update_origin = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateOrigin($var)
    {
        GPBUtil::checkEnum($var, \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUpdateOrigin::class);
        $this->update_origin = $var;

        return $this;
    }

    /**
     * What type of update was made.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType update_type = 6;</code>
     * @return int
     */
    public function getUpdateType()
    {
        return $this->update_type;
    }

    /**
     * What type of update was made.
     *
     * Generated from protobuf field <code>.google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType update_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateType($var)
    {
        GPBUtil::checkEnum($var, \Google\Events\Firebase\Remoteconfig\V1\RemoteConfigUpdateType::class);
        $this->update_type = $var;

        return $this;
    }

    /**
     * Only present if this version is the result of a rollback, and will be the
     * version number of the Remote Config template that was rolled-back to.
     *
     * Generated from protobuf field <code>int64 rollback_source = 7;</code>
     * @return int|string
     */
    public function getRollbackSource()
    {
        return $this->rollback_source;
    }

    /**
     * Only present if this version is the result of a rollback, and will be the
     * version number of the Remote Config template that was rolled-back to.
     *
     * Generated from protobuf field <code>int64 rollback_source = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRollbackSource($var)
    {
        GPBUtil::checkInt64($var);
        $this->rollback_source = $var;

        return $this;
    }

}

