<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/data.proto

namespace Google\Events\Firebase\Remoteconfig\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * All the fields associated with the person/service account
 * that wrote a Remote Config template.
 *
 * Generated from protobuf message <code>google.events.firebase.remoteconfig.v1.RemoteConfigUser</code>
 */
class RemoteConfigUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Display name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Email address.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * Image URL.
     *
     * Generated from protobuf field <code>string image_url = 3;</code>
     */
    protected $image_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Display name.
     *     @type string $email
     *           Email address.
     *     @type string $image_url
     *           Image URL.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Firebase\Remoteconfig\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * Display name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Display name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Email address.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Email address.
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Image URL.
     *
     * Generated from protobuf field <code>string image_url = 3;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return $this->image_url;
    }

    /**
     * Image URL.
     *
     * Generated from protobuf field <code>string image_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_url = $var;

        return $this;
    }

}

