<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/scheduler/v1/data.proto

namespace GPBMetadata\Google\Events\Cloud\Scheduler\V1;

class Data
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a2b676f6f676c652f6576656e74732f636c6f75642f7363686564756c65722f76312f646174612e70726f746f1220676f6f676c652e6576656e74732e636c6f75642e7363686564756c65722e763122270a105363686564756c65724a6f624461746112130a0b637573746f6d5f6461746118012001280c422caa0229476f6f676c652e4576656e74732e50726f746f6275662e436c6f75642e5363686564756c65722e5631620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

