<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/storage/v1/data.proto

namespace Google\Events\Cloud\Storage\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Storage\V1\StorageObjectData\CustomerEncryption instead.
     * @deprecated
     */
    class StorageObjectData_CustomerEncryption {}
}
class_exists(StorageObjectData\CustomerEncryption::class);
@trigger_error('Google\Events\Cloud\Storage\V1\StorageObjectData_CustomerEncryption is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Storage\V1\StorageObjectData\CustomerEncryption instead', E_USER_DEPRECATED);

