<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Cloudbuild\V1\BuildOptions\MachineType instead.
     * @deprecated
     */
    class BuildOptions_MachineType {}
}
class_exists(BuildOptions\MachineType::class);
@trigger_error('Google\Events\Cloud\Cloudbuild\V1\BuildOptions_MachineType is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Cloudbuild\V1\BuildOptions\MachineType instead', E_USER_DEPRECATED);

