<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Cloudbuild\V1\BuildOptions\VerifyOption instead.
     * @deprecated
     */
    class BuildOptions_VerifyOption {}
}
class_exists(BuildOptions\VerifyOption::class);
@trigger_error('Google\Events\Cloud\Cloudbuild\V1\BuildOptions_VerifyOption is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Cloudbuild\V1\BuildOptions\VerifyOption instead', E_USER_DEPRECATED);

