<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Cloudbuild\V1\BuildEventData\Status instead.
     * @deprecated
     */
    class BuildEventData_Status {}
}
class_exists(BuildEventData\Status::class);
@trigger_error('Google\Events\Cloud\Cloudbuild\V1\BuildEventData_Status is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Cloudbuild\V1\BuildEventData\Status instead', E_USER_DEPRECATED);

