<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Container message for hash values.
 *
 * Generated from protobuf message <code>google.events.cloud.cloudbuild.v1.Hash</code>
 */
class Hash extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of hash that was performed.
     *
     * Generated from protobuf field <code>.google.events.cloud.cloudbuild.v1.Hash.HashType type = 1;</code>
     */
    protected $type = 0;
    /**
     * The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           The type of hash that was performed.
     *     @type string $value
     *           The hash value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Events\Cloud\Cloudbuild\V1\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of hash that was performed.
     *
     * Generated from protobuf field <code>.google.events.cloud.cloudbuild.v1.Hash.HashType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The type of hash that was performed.
     *
     * Generated from protobuf field <code>.google.events.cloud.cloudbuild.v1.Hash.HashType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Google\Events\Cloud\Cloudbuild\V1\Hash_HashType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The hash value.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

}

