<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/cloudbuild/v1/data.proto

namespace Google\Events\Cloud\Cloudbuild\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Events\Cloud\Cloudbuild\V1\Hash\HashType instead.
     * @deprecated
     */
    class Hash_HashType {}
}
class_exists(Hash\HashType::class);
@trigger_error('Google\Events\Cloud\Cloudbuild\V1\Hash_HashType is deprecated and will be removed in the next major release. Use Google\Events\Cloud\Cloudbuild\V1\Hash\HashType instead', E_USER_DEPRECATED);

